
POST http://localhost:4000/api/login
Content-Type: application/json

{
  "email": "ihor@uplab.io",
  "password": "1234"
}

###

POST http://localhost:4000/api/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjIzNjg5NDY2LCJleHAiOjE2NTUyMjU0NjZ9.b7U0TKq38DebpbjjWM6uyHGrrKO9uXYnqn35Wa1szpA"
}

###

POST http://localhost:4000/api/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjIzNjg5NDY2LCJleHAiOjE2NTUyMjU0NjZ9.b7U0TKq38DebpbjjWM6uyHGrrKO9uXYnqn35Wa1szpA"
}

###

GET http://localhost:4000/api/hello
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxIiwiZW1haWwiOiJpaG9yQHVwbGFiLmlvIiwiaWF0IjoxNjIzNjg5NTA2LCJleHAiOjE2MjM2ODk4MDZ9.uPx-RoaI2QPS6hrBIWzFDZpqQowqnepesCrWw1fE-Fs



